services:
  redis:
    image: redis:7.2
    container_name: redis_server
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "{*{Kt_|5vIUk>>{;3wAe"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
