-- 1. Vaciar todas las tablas (Reset total)
TRUNCATE TABLE 
    ACCION_MODERACION,
    REPORTE,
    NOTIFICACION,
    CONFIGURACION_NOTIFICACION,
    CONFIGURACION_PRIVACIDAD,
    PREFERENCIA_MUSICAL,
    INVENTARIO,
    BLOQUEO,
    MENSAJE_CHAT,
    AMISTAD,
    INTERACCION,
    PUBLICACION,
    PERFIL,
    RECOMPENSA,
    USUARIO,
    CANCION,
    NIVEL
CASCADE;